service: 
  app:
    build: .
    ports:
      -"3000:3000"
    volume:
      - .:/app

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  db:
    image: postgres:12
    environnement:
      POSTGRS_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres 